### ISSUE TITLE
Add datasamples to repo to improve reproducibility of notebooks

### ISSUE THREAD

**Issue by cvitolo** [esowc/wildfire-forecasting#11]
Hello team!

At the moment the notebooks contain hardcoded file paths that refer to the Wekeo machine. 
It would be great to add data samples to this repo so that users and contributors can use the notebooks without necessarily have access to the data on Wekeo.

**Comment by roshni-b** [comment]
Hi @cvitolo 

This issue has been resolved and will be released as part of the code push scheduled later this week, wherein all the hard-coded paths referring to our internal WEkEO system have been removed; and a small subset of the data is accessible for EDA on the fly. This update will ensure complete reproducibility of our codebase.

**Comment by cvitolo** [comment]
Great, looking forward to the new release :)
