### ISSUE TITLE
docker-compose fails with pytorch-lightning

### ISSUE THREAD

**Issue by lazyoracle** [esowc/wildfire-forecasting#25]
# What
Running `docker-compose up --build` fails with the following error:

```bash
failed
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement pytorch_lightning==0.9.0rc12 (from -r /tmp/condaenv.6kgamfqf.requirements.txt (line 3)) (from versions: 0.0.2, 0.2, 0.2.2, 0.2.3, 0.2.4, 0.2.4.1, 0.2.5, 0.2.5.1, 0.2.5.2, 0.2.6, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.4.1, 0.3.5, 0.3.6, 0.3.6.1, 0.3.6.3, 0.3.6.4, 0.3.6.5, 0.3.6.6, 0.3.6.7, 0.3.6.8, 0.3.6.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.0, 0.5.1, 0.5.1.2, 0.5.1.3, 0.5.2, 0.5.2.1, 0.5.3, 0.5.3.1, 0.5.3.2, 0.5.3.3, 0.6.0, 0.7.1, 0.7.3, 0.7.5, 0.7.6, 0.8.1, 0.8.3, 0.8.4, 0.8.5, 0.9.0)
ERROR: No matching distribution found for pytorch_lightning==0.9.0rc12 (from -r /tmp/condaenv.6kgamfqf.requirements.txt (line 3))
CondaEnvException: Pip failed
ERROR: Service 'esowc-wildfire' failed to build: The command '/bin/bash --login -c conda update --name base --channel defaults conda &&     conda env create --prefix $ENV_PREFIX --file /tmp/environment.yml --force &&     conda clean --all --yes' returned a non-zero code: 1
```

# How to Reproduce
## System Info
`Linux wildfire1 4.19.0-9-cloud-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`

## Command
```bash
cd docker
docker-compose up --build
```

**Comment by roshni-b** [comment]
@lazyoracle: `wildfire1 is an instance name. 

Copying over the system info from #26:

<details>
<summary>System Info</summary>
<ul>
<li> OS: Debian GNU/Linux 10 (buster) </li>
<li> Version: # 1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) </li>
<li> Kernel: 4.19.0-9-cloud-amd64 </li>
<li> Architecture: x86_64 </li>
<li> Python: 3.7.6 </li>
</ul>
</details>

**Comment by roshni-b** [comment]
@lazyoracle: `wildfire1` is an instance name. 

Copying over the system info from #26:

<details>
<summary>System Info</summary>
<ul>
<li> OS: Debian GNU/Linux 10 (buster) </li>
<li> Version: # 1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) </li>
<li> Kernel: 4.19.0-9-cloud-amd64 </li>
<li> Architecture: x86_64 </li>
<li> Python: 3.7.6 </li>
</ul>
</details>
