### ISSUE TITLE
Size Mismatch Error in examples

### ISSUE THREAD

**Issue by Gunnika** [esowc/wildfire-forecasting#43]
Hi
I've set up the Wikilimo project according to the instructions on a Ubuntu 20.04 WSL 2 machine.
I'm facing a size mismatch error while running the examples provided. Attaching screenshots of the error in both examples below. 
Any leads will be appreciated!

![Inference_2_1](https://user-images.githubusercontent.com/34855465/97082938-bff6eb80-162a-11eb-9dbe-988dcca95e39.png)
![Inference_4_1](https://user-images.githubusercontent.com/34855465/97082943-c4230900-162a-11eb-8de2-b21512fb92a7.png)

**Comment by roshni-b** [comment]
Hi Gunnika, 

We were unable to reproduce the size mismatch error above. We've had some recent developments and refactoring in our codebase, and I'd suggest you check out our newly released notebooks demonstrating [2_1 Inference](https://github.com/esowc/wildfire-forecasting/blob/master/examples/Inference_2_1.ipynb) and [4_10 Inference](https://github.com/esowc/wildfire-forecasting/blob/master/examples/Inference_4_10.ipynb). Let us know if you face any trouble running them using the newly updated pre-trained model & sample datasets specified. 

Hope this helps!

**Comment by lazyoracle** [comment]
Hi @Gunnika We hope you were able to resolve the issue with the latest code. We are closing the issue now for lack of activity, please feel free to reopen this if you would like to discuss further.
