### ISSUE TITLE
BucketNotFoundException: 404 gs://deepgeff-data-v0 bucket does not exist.

### ISSUE THREAD

**Issue by 99snowleopards** [esowc/wildfire-forecasting#53]
**Describe the bug**

I'm getting the error:

`BucketNotFoundException: 404 gs://deepgeff-data-v0 bucket does not exist.`

**To Reproduce**
1. Go to https://github.com/esowc/wildfire-forecasting/blob/master/examples/Inference_2_1.ipynb 
2. run `gsutil cp` command 
3. see error:
`BucketNotFoundException: 404 gs://deepgeff-data-v0 bucket does not exist.`

**Expected behavior**
copy the data

thank you for releasing the code  @roshni-b @lazyoracle  - would it be possible to make the GCS bucket with the sample data public again please - thank you

**Comment by lazyoracle** [comment]
Unfortunately the specific dataset has now been made private. You can check out alternate similar data sources from the ECMWF Copernicus Date Store. The notebooks contain some elementary documentation on how to structure the data files such that they can be consumed by the code.

**Comment by 99snowleopards** [comment]
thank you for the quick response @lazyoracle  - would it be possible to access the pre-trained models that were available at:
`gs://deepgeff-models-v0` 

if possible at all, it'd help greatly if we could access some extremely small files that could be added to the github repo

thanks again for sharing this great work
